### ISSUE TITLE
'no route to host' when running nfs-provisioner as a pod from hack/local-up-cluster.sh

### ISSUE THREAD

**Issue by childsb** [wongma7/nfs-provisioner#3]
I'm running kube on a single node with:

` ALLOW_SECURITY_CONTEXT=true API_HOST=0.0.0.0 KUBE_ENABLE_CLUSTER_DNS=true hack/local-up-cluster.sh`

I create a storageClass:
```yaml
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: nfs-default
provisioner: matthew/nfs 
parameters:
```

deploy the NFS pod:

`kubectl create -f deploy/kube-config/pod.yaml `

Then create a claim:
```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sc-claim 
  annotations:
    volume.beta.kubernetes.io/storage-class: nfs-default 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
```

No PV is created and the PVC sticks in pending.  The logs for the provisioner show:

I1101 01:44:54.234496       1 main.go:55] Provisioner matthew/nfs specified
I1101 01:44:54.236293       1 main.go:64] Starting NFS server!
I1101 01:44:54.568961       1 controller.go:192] Starting nfs provisioner controller!
E1101 01:44:55.575485       1 reflector.go:214] github.com/wongma7/nfs-provisioner/vendor/k8s.io/client-go/1.4/tools/cache/reflector.go:109: Failed to list *v1beta1.StorageClass: Get https://10.0.0.1:443/apis/storage.k8s.io/v1beta1/storageclasses?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E1101 01:44:55.575798       1 reflector.go:214] github.com/wongma7/nfs-provisioner/vendor/k8s.io/client-go/1.4/tools/cache/reflector.go:109: Failed to list *v1.PersistentVolumeClaim: Get https://10.0.0.1:443/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E1101 01:44:55.575956       1 reflector.go:214] github.com/wongma7/nfs-provisioner/vendor/k8s.io/client-go/1.4/tools/cache/reflector.go:109: Failed to list *v1.PersistentVolume: Get https://10.0.0.1:443/api/v1/persistentvolumes?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
E1101 01:44:57.578821       1 reflector.go:214] github.com/wongma7/nfs-provisioner/vendor/k8s.io/client-go/1.4/tools/cache/reflector.go:109: Failed to list *v1.PersistentVolumeClaim: Get https://10.0.0.1:443/api/v1/persistentvolumeclaims?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: no route to host
....
